print("welcome to 3p1kpwnner by thelittlemonke (Karim Xuzin) ver.2.0.0")
print("_____       __  _                                        ")
print("|____ |     /  || |                                       ")
print("/ /_ __ `| || | ___ ____      ___ __  _ __   ___ _ __ ")
print("\ \ '_ \ | || |/ / '_ \ \ /\ / / '_ \| '_ \ / _ \ '__|")
print(".___/ / |_) || ||   <| |_) \ V  V /| | | | | | |  __/ |   ")
print("\____/| .__/\___/_|\_\ .__/ \_/\_/ |_| |_|_| |_|\___|_|   ")
print("| |            | |                                  ")
print("|_|            |_|                                  ")

myinput = input("who would you like to pwn? ")

print('pwnning ' + myinput + " ...")
import time
print("searching {myinput} account`s...")
time.sleep(4)
print("found 37 accounts total. proceeding with pwnning")
time.sleep(1)
print("> starting to spam telegram using encrypted ttcp to udp connection")
time.sleep(1)
print("> generating fake images with uncencsored local model LLM ai")
time.sleep(1)
print("> connecting to his pc thru backd00r")
time.sleep(1)
print("> deleting bank account")
time.sleep(1)
print("> pwnn1ng his phone number l0l")
time.sleep(1)
print("> leaving mark elite 1337 h1x0r")
time.sleep(1)
print("> leaving info on doxbin")
time.sleep(1)
print("> wiping his pc rm rf")
time.sleep(4)
print(myinput + "was pwnned hard af 😎😎😎😎")
print(" ________  ___       __   ________   ________   _______   ________         ")
print("|\   __  \|\  \     |\  \|\   ___  \|\   ___  \|\  ___ \ |\   ___ \        ")
print("\ \  \|\  \ \  \    \ \  \ \  \\ \  \ \  \\ \  \ \   __/|\ \  \_|\ \       ")
print(" \ \   ____\ \  \  __\ \  \ \  \\ \  \ \  \\ \  \ \  \_|/_\ \  \ \\ \      ")
print("  \ \  \___|\ \  \|\__\_\  \ \  \\ \  \ \  \\ \  \ \  \_|\ \ \  \_\\ \     ")
print("   \ \__\    \ \____________\ \__\\ \__\ \__\\ \__\ \_______\ \_______\    ")
print("    \|__|     \|____________|\|__| \|__|\|__| \|__|\|_______|\|_______|    ")
print("                                                                           ")
print("                                                                           ")
print("                                                                           ")